apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hermyz-http
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: api.slack.hermyz.com
    http:
      paths:
      - backend:
          serviceName: hermyz-service-prod
          servicePort: 80
        path: /api/v1